apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: webapp-dev
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
    - port: 3000
  selector:
    app: webapp
