apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: webapp-dev
      context: webapp
      sync:
        manual:
          - src: ./src/webapp/core.clj
            dest: /usr/src/app/src/
deploy:
  kubectl:
    manifests:
      - k8s-*
