apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: webapp-dev
      context: webapp
      sync:
        infer:
          - '**/*'
deploy:
  kubectl:
    manifests:
      - k8s-*
